[build]
  publish = "."
  command = ""

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production]
  command = ""

[context.deploy-preview]
  command = ""

[context.branch-deploy]
  command = ""

[dev]
  publish = "."
  port = 3000
